In [ ]:
Question 1: Array Creation and Manipulation
Q1.1: Create a 4x4 identity matrix using np.eye()

Q1.2: Create an array of 8 zeros using np.zeros()

Q1.3: Create an array of 6 ones using np.ones()

Q1.4: Create an array with values from 0 to 15 using np.arange()

Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

Question 2: Array Attributes and Information
Q2.1: What is the shape of the banking_data array?

Q2.2: What is the data type of the banking_data array?

Q2.3: What is the size (total number of elements) of the banking_data array?

Q2.4: What is the number of dimensions of the banking_data array?

Q2.5: What is the memory size of the banking_data array in bytes?

Question 3: Indexing and Slicing
Q3.1: Extract the first row of banking_data

Q3.2: Extract the last row of banking_data

Q3.3: Extract the Account_Balance column (column index 1)

Q3.4: Extract the first 4 rows and first 3 columns

Q3.5: Extract rows 3 to 7 (inclusive)

Question 4: Mathematical Operations
Q4.1: Calculate the sum of all account balances

Q4.2: Calculate the mean account balance

Q4.3: Calculate the standard deviation of account balances

Q4.4: Calculate the variance of account balances

Q4.5: Calculate the median account balance

Question 5: Statistical Functions
Q5.1: Find the minimum and maximum account balances

Q5.2: Find the minimum and maximum credit scores

Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)

Q5.4: Calculate the correlation between account balance and credit score

Q5.5: Calculate the covariance between account balance and credit score

Question 6: Array Reshaping and Manipulation
Q6.1: Reshape the banking_data to 5 rows × 10 columns

Q6.2: Flatten the banking_data to a 1D array

Q6.3: Transpose the banking_data

Q6.4: Split the banking_data into 2 equal parts vertically

Q6.5: Split the banking_data into 2 equal parts horizontally

Question 7: Logical Operations and Filtering
Q7.1: Find customers with account balance greater than $100,000

Q7.2: Find customers with credit score greater than 800

Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750

Q7.4: Count how many customers have account balance between $10,000 and $100,000

Q7.5: Find the index of the customer with the highest credit score

Question 8: Sorting and Searching
Q8.1: Sort the banking_data by account balance (ascending)

Q8.2: Sort the banking_data by credit score (descending)

Q8.3: Find the indices that would sort the array by years active

Q8.4: Find the customer with the second highest account balance

Q8.5: Find the customer with the lowest transaction count

Question 9: Mathematical Functions
Q9.1: Calculate the absolute values of all elements

Q9.2: Calculate the square root of all account balances

Q9.3: Calculate the square of all credit scores

Q9.4: Calculate the exponential of all transaction counts

Q9.5: Calculate the natural logarithm of all account balances

Question 10: Advanced Operations
Q10.1: Calculate the cumulative sum of account balances

Q10.2: Calculate the cumulative product of transaction counts

Q10.3: Calculate the difference between consecutive account balances

Q10.4: Calculate the gradient of account balances

Q10.5: Calculate the histogram of account balances with 5 bins

Question 11: Random Numbers and Simulation
Q11.1: Generate 6 random integers between 1 and 1000

Q11.2: Generate 6 random floats between 0 and 1

Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)

Q11.4: Shuffle the banking_data rows randomly

Q11.5: Set random seed to 123 and generate 4 random numbers

Question 12: Linear Algebra Operations
Q12.1: Calculate the dot product of account balance and credit score columns

Q12.2: Calculate the cross product of first two rows

Q12.3: Calculate the norm (magnitude) of the account balance column

Q12.4: Create a 3x3 matrix and calculate its determinant

Q12.5: Calculate the inverse of the 3x3 matrix

Question 13: String Operations
Q13.1: Convert all customer IDs to strings

Q13.2: Check if any customer ID contains '100'

Q13.3: Convert all customer IDs to uppercase (if they were strings)

Q13.4: Count the length of each customer ID string

Q13.5: Replace '100' with 'CUST' in customer IDs

Question 14: Date and Time Operations
Q14.1: Convert years active to months

Q14.2: Calculate the average years active

Q14.3: Find customers who have been active for more than 5 years

Q14.4: Calculate the total time all customers have been active (in years)

Q14.5: Find the customer with the shortest time active

Question 15: Advanced Array Operations
Q15.1: Apply a function to calculate 5% interest on all account balances

Q15.2: Use np.where to categorize customers by balance ranges

Q15.3: Use np.select to categorize customers by credit score ranges

Q15.4: Use np.piecewise to apply different interest rates based on balance

Q15.5: Use np.apply_along_axis to calculate the sum of each row

Question 16: Array Concatenation and Stacking
Q16.1: Concatenate two arrays horizontally using np.hstack()

Q16.2: Concatenate two arrays vertically using np.vstack()

Q16.3: Concatenate arrays along a specific axis using np.concatenate()

Q16.4: Stack arrays depth-wise using np.dstack()

Q16.5: Create a column stack using np.column_stack()

Question 17: Array Splitting Operations
Q17.1: Split an array into 3 equal parts using np.split()

Q17.2: Split an array at specific indices using np.split()

Q17.3: Split an array horizontally using np.hsplit()

Q17.4: Split an array vertically using np.vsplit()

Q17.5: Split an array into equal chunks using np.array_split()

Question 18: Array Repetition and Tiling
Q18.1: Repeat each element of an array 3 times using np.repeat()

Q18.2: Repeat an entire array 2 times using np.tile()

Q18.3: Repeat a 2D array using np.tile()

Q18.4: Create a pattern using np.tile()

Q18.5: Repeat elements with different counts using np.repeat()

Question 19: Array Comparison and Logical Operations
Q19.1: Compare two arrays for equality using np.array_equal()

Q19.2: Check if arrays are close using np.allclose()

Q19.3: Apply logical AND operation between arrays

Q19.4: Apply logical OR operation between arrays

Q19.5: Apply logical NOT operation to an array

Question 20: Array Set Operations
Q20.1: Find unique elements in an array using np.unique()

Q20.2: Find the intersection of two arrays using np.intersect1d()

Q20.3: Find the union of two arrays using np.union1d()

Q20.4: Find elements in first array but not in second using np.setdiff1d()

Q20.5: Find the symmetric difference between two arrays using np.setxor1d()



In [ ]:
# Q1.1: Create a 4x4 identity matrix using np.eye()
import numpy as np
identity_matrix=np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Q1.2: Create an array of 8 zeros using np.zeros()
import numpy as np
zeroes_array=np.zeros(8)
print(zeroes_array)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Q1.3: Create an array of 6 ones using np.ones()
import numpy as np
ones_array=np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [ ]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
import numpy as np
range_array=np.arange(16)
print(range_array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
import numpy as np
linspace_array=np.linspace(0,100,8)
print(linspace_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [ ]:
#customer_id,Account_Balance,Credit_Score,Transaction_count,Years_active
banking_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(banking_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
Question2

In [ ]:
# Q2.1: What is the shape of the banking_data array?
print(f"shape:{banking_data.shape}")

shape:(10, 5)


In [ ]:
# Q2.2: What is the data type of the banking_data array?
print(f"datatype:{banking_data.dtype}")

datatype:int64


In [ ]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
print(f"size:{banking_data.size}")

size:50


In [ ]:
# Q2.4: What is the number of dimensions of the banking_data array?
print(f"dimensions:{banking_data.ndim}")

dimensions:2


In [ ]:
# Q2.5: What is the memory size of the banking_data array in bytes?
print(f"memory size:{banking_data.nbytes}")


memory size:400


In [ ]:
Question 3

In [ ]:
# Q3.1: Extract the first row of banking_data
first_row=banking_data[0]
print(first_row)

[    1 25000   300  1200    10]


In [ ]:
# Q3.2: Extract the last row of banking_data
last_row=banking_data[-1]
print(last_row)

[   10 33000   410  1450    11]


In [ ]:
# Q3.3: Extract the Account_Balance column (column index 1)
Account_Balance=banking_data[:,1]
print(Account_Balance)

[25000 32000 28000 41000 35000 27000 39000 30000 45000 33000]


In [ ]:
# Q3.4: Extract the first 4 rows and first 3 columns
first_4_rows=banking_data[:4,:3]
print(first_4_rows)

[[    1 25000   300]
 [    2 32000   450]
 [    3 28000   380]
 [    4 41000   500]]


In [ ]:
# Q3.5: Extract rows 3 to 7 (inclusive)
rows_3_to_7=banking_data[3:8]
print(rows_3_to_7)

[[    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]]


In [ ]:
print(banking_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
Question 4

In [ ]:
print(banking_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# Q4.1: Calculate the sum of all account balances
import numpy as np
sum_account=np.sum(banking_data[:,1])
print(sum_account)

335000


In [ ]:
# Q4.2: Calculate the mean account balance
mean_account=np.mean(banking_data[:,1])
print(mean_account)


33500.0


In [ ]:
# Q4.3: Calculate the standard deviation of account balances
std_account=np.std(banking_data[:,1])
print(std_account)


6168.468205316454


In [ ]:
# Q4.4: Calculate the variance of account balances
variance=np.var(banking_data[:,1])
print(variance)

38050000.0


In [ ]:
# Q4.5: Calculate the median account balance
median=np.median(banking_data[:,1])
print(median)

32500.0


In [ ]:
# Question 5: Statistical Functions

# Q5.1: Find the minimum and maximum account balances
min_account=np.min(banking_data[:,1])
max_account=np.max(banking_data[:,1])
print(min_account)
print(max_account)

25000
45000


In [ ]:
# Q5.2: Find the minimum and maximum credit scores
min_credit=np.min(banking_data[:,2])
max_credit=np.max(banking_data[:,2])
print(min_credit)
print(max_credit)

300
550


In [ ]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
per_values=np.percentile(banking_data[:,1],[25,50,75])
print(per_values)

[28500. 32500. 38000.]


In [ ]:
# Q5.4: Calculate the correlation between account balance and credit score
correlation=np.corrcoef(banking_data[:,1],banking_data[:,2])[0,1]
print(correlation)

0.9593636912502479


In [ ]:
# Q5.5: Calculate the covariance between account balance and credit score
covariance=np.cov(banking_data[:,1],banking_data[:,2])[0,1]
print(covariance)

453888.8888888889


In [ ]:
# Question 6: Array Reshaping and Manipulation

# Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshaped_data=np.reshape(banking_data,(5,10))
print(reshaped_data)


[[    1 25000   300  1200    10     2 32000   450  1500    15]
 [    3 28000   380  1100     8     4 41000   500  1600    20]
 [    5 35000   420  1400    12     6 27000   360  1300     9]
 [    7 39000   480  1700    18     8 30000   400  1250    14]
 [    9 45000   550  1800    25    10 33000   410  1450    11]]


In [ ]:
# Q6.2: Flatten the banking_data to a 1D array
flatting_data=banking_data.flatten()
print(flatting_data)

[    1 25000   300  1200    10     2 32000   450  1500    15     3 28000
   380  1100     8     4 41000   500  1600    20     5 35000   420  1400
    12     6 27000   360  1300     9     7 39000   480  1700    18     8
 30000   400  1250    14     9 45000   550  1800    25    10 33000   410
  1450    11]


In [ ]:
# Q6.3: Transpose the banking_data
transposed_data=banking_data.T
print(transposed_data)

[[    1     2     3     4     5     6     7     8     9    10]
 [25000 32000 28000 41000 35000 27000 39000 30000 45000 33000]
 [  300   450   380   500   420   360   480   400   550   410]
 [ 1200  1500  1100  1600  1400  1300  1700  1250  1800  1450]
 [   10    15     8    20    12     9    18    14    25    11]]


In [ ]:
# Q6.4: Split the banking_data into 2 equal parts vertically
split_data=np.vsplit(banking_data,2)
print(split_data[0])
print(split_data[1])

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]]
[[    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
split_data=np.hsplit(banking_data,2)
print(split_data[0])
print(split_data[1])

In [ ]:
print(banking_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# Question 7: Logical Operations and Filtering
# Q7.1: Find customers with account balance greater than $100,000
cus=banking_data[(banking_data[:,1]>10000)]
print(cus)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# Q7.2: Find customers with credit score greater than 800
cus=banking_data[banking_data[:,2]>800]
print(cus)

[]


In [ ]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
cus=banking_data[(banking_data[:,3]>50) & (banking_data[:,2]<750)]
print(cus)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
cus=np.sum((banking_data[:,1]>=10000) & (banking_data[:,1] <=100000))
print(cus)

10


In [ ]:
# Q7.5: Find the index of the customer with the highest credit score
index=np.argmax(banking_data[:,2])+1
print(index)

9


In [ ]:
# Question 8: Sorting and Searching
# Q8.1: Sort the banking_data by account balance (ascending)
sorted_data=banking_data[banking_data[:,1].argsort()]
print(sorted_data)



[[    1 25000   300  1200    10]
 [    6 27000   360  1300     9]
 [    3 28000   380  1100     8]
 [    8 30000   400  1250    14]
 [    2 32000   450  1500    15]
 [   10 33000   410  1450    11]
 [    5 35000   420  1400    12]
 [    7 39000   480  1700    18]
 [    4 41000   500  1600    20]
 [    9 45000   550  1800    25]]


In [ ]:
# Q8.2: Sort the banking_data by credit score (descending)
sorted_data=banking_data[banking_data[:,2].argsort()[::-1]]
print(sorted_data)


[[    9 45000   550  1800    25]
 [    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    2 32000   450  1500    15]
 [    5 35000   420  1400    12]
 [   10 33000   410  1450    11]
 [    8 30000   400  1250    14]
 [    3 28000   380  1100     8]
 [    6 27000   360  1300     9]
 [    1 25000   300  1200    10]]


In [ ]:
# Q8.3: Find the indices that would sort the array by years active
indices=np.argsort(banking_data[:,4])
print(indices)

[2 5 0 9 4 7 1 6 3 8]


In [ ]:
# Q8.4: Find the customer with the second highest account balance
second_highest=banking_data[np.argsort(banking_data[:,1])[-2]]
print(second_highest)

[    4 41000   500  1600    20]


In [ ]:
# Q8.5: Find the customer with the lowest transaction count
lowest_transaction=banking_data[np.argmin(banking_data[:,3])]
print(lowest_transaction)

[    3 28000   380  1100     8]


In [ ]:
# Question 9: Mathematical Functions
# Q9.1: Calculate the absolute values of all elements
absolute_values=np.abs(banking_data)
print(absolute_values)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# Q9.2: Calculate the square root of all account balances
square_root=np.sqrt(banking_data[:,1])
print(square_root)


[158.11388301 178.8854382  167.33200531 202.48456731 187.08286934
 164.31676725 197.48417658 173.20508076 212.13203436 181.65902125]


In [ ]:
# Q9.3: Calculate the square of all credit scores
square=np.square(banking_data[:,2])
print(square)


[ 90000 202500 144400 250000 176400 129600 230400 160000 302500 168100]


In [ ]:
# Q9.4: Calculate the exponential of all transaction counts
exponential=np.exp(banking_data[:,3])
print(exponential)

[inf inf inf inf inf inf inf inf inf inf]


/tmp/ipython-input-2681035716.py:2: RuntimeWarning: overflow encountered in exp
  exponential=np.exp(banking_data[:,3])


In [ ]:
# Q9.5: Calculate the natural logarithm of all account balances
natural_log=np.log(banking_data[:,1])
print(natural_log)

[10.1266311  10.37349118 10.23995979 10.62132735 10.46310334 10.20359214
 10.57131693 10.30895266 10.71441777 10.40426284]


In [ ]:
# Question 10: Advanced Operations
# Q10.1: Calculate the cumulative sum of account balances
cumulative_sum=np.cumsum(banking_data[:,1])
print(cumulative_sum)



[ 25000  57000  85000 126000 161000 188000 227000 257000 302000 335000]


In [ ]:
# Q10.2: Calculate the cumulative product of transaction counts
cumulative_product=np.cumprod(banking_data[:,3])
print(cumulative_product)

[                1200              1800000           1980000000
        3168000000000     4435200000000000  5765760000000000000
  6570896860228091904  4819962484364410880  5962757212450324480
 -5525012516809211904]


In [ ]:
# Q10.3: Calculate the difference between consecutive account balances
difference=np.diff(banking_data[:,1])
print(difference)


[  7000  -4000  13000  -6000  -8000  12000  -9000  15000 -12000]


In [ ]:
# Q10.4: Calculate the gradient of account balances
gradient=np.gradient(banking_data[:,1])
print(gradient)

[  7000.   1500.   4500.   3500.  -7000.   2000.   1500.   3000.   1500.
 -12000.]


In [ ]:
# Q10.5: Calculate the histogram of account balances with 5 bins
histogram=np.histogram(banking_data[:,1],bins=5)
print(histogram)

(array([3, 2, 2, 1, 2]), array([25000., 29000., 33000., 37000., 41000., 45000.]))


In [ ]:
# Question 11: Random Numbers and Simulation
# Q11.1: Generate 6 random integers between 1 and 1000
random_integers=np.random.randint(1,1001,6)
print(random_integers)

[503 213 172 553 105 285]


In [ ]:
# Q11.2: Generate 6 random floats between 0 and 1
random_floats=np.random.rand(6)
print(random_floats)


[0.69789011 0.24433896 0.60542344 0.10085707 0.05700354 0.96715406]


In [ ]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
random_normal=np.random.normal(700,100,6)
print(random_normal)

[762.08025678 664.10930959 633.52213344 576.84834995 772.66953548
 695.17873961]


In [ ]:

# Q11.4: Shuffle the banking_data rows randomly
np.random.shuffle(banking_data)
print(banking_data)

[[    3 28000   380  1100     8]
 [    9 45000   550  1800    25]
 [    2 32000   450  1500    15]
 [    4 41000   500  1600    20]
 [    8 30000   400  1250    14]
 [   10 33000   410  1450    11]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    1 25000   300  1200    10]
 [    5 35000   420  1400    12]]


In [ ]:
# Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
random_numbers=np.random.rand(4)
print(random_numbers)

[0.69646919 0.28613933 0.22685145 0.55131477]


In [ ]:
# Question 12: Linear Algebra Operations
# Q12.1: Calculate the dot product of account balance and credit score columns
dot_product=np.dot(banking_data[:,1],banking_data[:,2])
print(dot_product)

146460000


In [ ]:
print(banking_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# Q12.2: Calculate the cross product of first two rows
import numpy as np
cross_product=np.cross(banking_data[0, :3],banking_data[1, :3])
print(cross_product)

[1650000     150  -18000]


In [ ]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
norm=np.linalg.norm(banking_data[:,1])
print(norm)

107717.22239270747


In [ ]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix=np.array([[5,2,3],[4,5,6],[7,8,9]])
determinant=np.linalg.det(matrix)
print(matrix)
print(determinant)

[[5 2 3]
 [4 5 6]
 [7 8 9]]
-12.0


In [ ]:
# Q12.5: Calculate the inverse of the 3x3 matrix
inverse=np.linalg.inv(matrix)
print(inverse)

[[ 0.25       -0.5         0.25      ]
 [-0.5        -2.          1.5       ]
 [ 0.25        2.16666667 -1.41666667]]


In [ ]:
# Question 13: String Operations
# Q13.1: Convert all customer IDs to strings
customer_ids=banking_data[:,0].astype(str)
print(customer_ids)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [ ]:
# Q13.2: Check if any customer ID contains '100'
data=np.char.find(customer_ids, '100') >= 0
print(banking_data[data])


[]


In [ ]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
upper_case=np.char.upper(customer_ids)
print(upper_case)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [ ]:
# Q13.4: Count the length of each customer ID string
length=np.char.str_len(customer_ids)
print(length)

[1 1 1 1 1 1 1 1 1 2]


In [ ]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
replace=np.char.replace(customer_ids,'100','CUST')
print(replace)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [ ]:
# Question 14: Date and Time Operations
# Q14.1: Convert years active to months
banking_data[:,4]=banking_data[:,4]*12
print(banking_data)

[[    1 25000   300  1200   120]
 [    2 32000   450  1500   180]
 [    3 28000   380  1100    96]
 [    4 41000   500  1600   240]
 [    5 35000   420  1400   144]
 [    6 27000   360  1300   108]
 [    7 39000   480  1700   216]
 [    8 30000   400  1250   168]
 [    9 45000   550  1800   300]
 [   10 33000   410  1450   132]]


In [ ]:
# Q14.2: Calculate the average years active
average=np.mean(banking_data[:,4])
print(average)

170.4


In [ ]:
# Q14.3: Find customers who have been active for more than 5 years
active=banking_data[banking_data[:,4]>5]
print(active)


[[    1 25000   300  1200   120]
 [    2 32000   450  1500   180]
 [    3 28000   380  1100    96]
 [    4 41000   500  1600   240]
 [    5 35000   420  1400   144]
 [    6 27000   360  1300   108]
 [    7 39000   480  1700   216]
 [    8 30000   400  1250   168]
 [    9 45000   550  1800   300]
 [   10 33000   410  1450   132]]


In [ ]:
# Q14.4: Calculate the total time all customers have been active (in years)
total_time=np.sum(banking_data[:,4])
print(total_time)

1704


In [ ]:
# Q14.5: Find the customer with the shortest time active
customer_shortest_active=np.argmin(banking_data[:,4])
shortest_cus_active=banking_data[customer_shortest_active]
print(shortest_cus_active)

[    3 28000   380  1100    96]


In [ ]:
# Question 15: Advanced Array Operations
# Q15.1: Apply a function to calculate 5% interest on all account balances
interest=banking_data[:,1]*0.05
print(interest)

[1250. 1600. 1400. 2050. 1750. 1350. 1950. 1500. 2250. 1650.]


In [ ]:
print(banking_data)

[[    1 25000   300  1200   120]
 [    2 32000   450  1500   180]
 [    3 28000   380  1100    96]
 [    4 41000   500  1600   240]
 [    5 35000   420  1400   144]
 [    6 27000   360  1300   108]
 [    7 39000   480  1700   216]
 [    8 30000   400  1250   168]
 [    9 45000   550  1800   300]
 [   10 33000   410  1450   132]]


In [ ]:
# Q15.2: Use np.where to categorize customers by balance ranges
bal=np.where(banking_data[:,1]>30000,'High','Low')
print(bal)

['Low' 'High' 'Low' 'High' 'High' 'Low' 'High' 'Low' 'High' 'High']


In [ ]:
# Q15.3: Use np.select to categorize customers by credit score ranges
conditions=[banking_data[:, 4] <100,
            (banking_data[:, 4] >=200) & (banking_data[:, 4] <250),
            banking_data[:, 4] >=300
]
choices=['poor','average','good']
credit_score=np.select(conditions,choices,default='unknown')
print(credit_score)

['unknown' 'unknown' 'poor' 'average' 'unknown' 'unknown' 'average'
 'unknown' 'good' 'unknown']


In [ ]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance
def low_interest(x): return x *1.05
def average_interest(x): return x *1.10
def high_interest(x): return x *1.15
interest_rates=np.piecewise( banking_data[:, 1], [banking_data[:,1] < 20000, (banking_data[:, 1] >= 20000) & (banking_data[:, 1] < 30000), banking_data[:,1] >= 30000],
                                                  [low_interest,average_interest,high_interest])
print(interest_rates)

[27500 36800 30800 47149 40250 29700 44850 34500 51749 37950]


In [ ]:
# Q15.5: Use np.apply_along_axis to calculate the sum of each row
row_sums=np.apply_along_axis(np.sum, 1, banking_data)
print(row_sums)

[26621 34132 29579 43344 36969 28774 41403 31826 47659 35002]


In [ ]:
# Question 16: Array Concatenation and Stacking
# Q16.1: Concatenate two arrays horizontally using np.hstack()
import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])
horizontal_array=np.hstack((array1,array2))
print(horizontal_array)

[1 2 3 4 5 6]


In [ ]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
vertical_array=np.vstack((array1,array2))
print(vertical_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
concatenated_array=np.concatenate((array1,array2),axis=0)
print(concatenated_array)

[1 2 3 4 5 6]


In [ ]:
# Q16.4: Stack arrays depth-wise using np.dstack()
depth_stack=np.dstack((array1,array2))
print(depth_stack)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
# Q16.5: Create a column stack using np.column_stack()
column_stack=np.column_stack((array1,array2))
print(column_stack)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Question 17: Array Splitting Operations
# Q17.1: Split an array into 3 equal parts using np.split()
array=np.array([1,2,3,4,5,6])
split_array=np.split(array,3)
print(split_array)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Q17.2: Split an array at specific indices using np.split()
array= np.array([1,2,3,4,5,6,7,8])
split_array=np.split(array,[2,5])
print(split_array)

[array([1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [ ]:
# Q17.3: Split an array horizontally using np.hsplit()
array=np.array([[1,2,3],[4,5,6]])
split_array=np.hsplit(array,3)
print(split_array)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [ ]:
# Q17.4: Split an array vertically using np.vsplit()
array=np.array([[1,2,3],[4,5,6]])
split_array=np.vsplit(array,2)
print(split_array)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
# Q17.5: Split an array into equal chunks using np.array_split()
array=np.array([1,2,3,4,5,6])
split_array=np.array_split(array,3)
print(split_array)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Question 18: Array Repetition and Tiling
# Q18.1: Repeat each element of an array 3 times using np.repeat()
array=np.array([1,2,3])
repeated_array=np.repeat(array,3)
print(repeated_array)

[1 1 1 2 2 2 3 3 3]


In [ ]:
# Q18.2: Repeat an entire array 2 times using np.tile()
tiled_array=np.tile(array,2)
print(tiled_array)

[1 2 3 1 2 3]


In [ ]:
# Q18.3: Repeat a 2D array using np.tile()
array=np.array([[1,2],[3,4]])
tiled_array=np.tile(array,(2,2))
print(tiled_array)

[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [ ]:
# Q18.4: Create a pattern using np.tile()
pattern=np.array([[0,1],[1,0]])
tiled_pattern=np.tile(pattern,(4,4))
print(tiled_pattern)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Q18.5: Repeat elements with different counts using np.repeat()
array=np.array([1,2,3])
repeated_array=np.repeat(array,[1,2,3])
print(repeated_array)

[1 2 2 3 3 3]


In [ ]:
# Question 19: Array Comparison and Logical Operations
# Q19.1: Compare two arrays for equality using np.array_equal()
array1=np.array([1,2,3])
array2=np.array([1,2,3])
equal=np.array_equal(array1,array2)
print(equal)

True


In [ ]:
# Q19.2: Check if arrays are close using np.allclose()
array1=np.array([1,2,3])
array2=np.array([1,2,3])
close=np.allclose(array1,array2)
print(close)

True


In [ ]:
# Q19.3: Apply logical AND operation between arrays
array1=np.array([True,True,False])
array2=np.array([True,False,True])
logical_and=np.logical_and(array1,array2)
print(logical_and)


[ True False False]


In [ ]:
# Q19.4: Apply logical OR operation between arrays
logical_or=np.logical_or(array1,array2)
print(logical_or)

[ True  True  True]


In [ ]:
# Q19.5: Apply logical NOT operation to an array
logical_not=np.logical_not(array1)
print(logical_not)


[False False  True]


In [ ]:
# Question 20: Array Set Operations
# Q20.1: Find unique elements in an array using np.unique()
array=np.array([1,2,3,2,1,4,5,4])
unique_elements=np.unique(array)
print(unique_elements)

[1 2 3 4 5]


In [ ]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
array1=np.array([1,2,3,4,5])
array2=np.array([3,4,5,6,7])
intersection=np.intersect1d(array1,array2)
print(intersection)

[3 4 5]


In [ ]:
# Q20.3: Find the union of two arrays using np.union1d()
union=np.union1d(array1,array2)
print(union)

[1 2 3 4 5 6 7]


In [ ]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
difference=np.setdiff1d(array1,array2)
print(difference)

[1 2]


In [ ]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
symmetric_difference=np.setxor1d(array1,array2)
print(symmetric_difference)

[1 2 6 7]
