In [3]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
**Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis
1. What is the **total revenue** generated across all stores?
2. Which store recorded the **highest sales**?
3. Which store recorded the **lowest sales**?
4. What is the **average daily sales** per store?
5. How many stores achieved sales **above ₹35,000**?

## Customer Insights
6. Which store had the **highest customer footfall**?
7. What is the **average number of customers** per store?
8. How many stores have **more than 450 customers**?
9. Which store has the **lowest customer count**?
10. Is there any store where **high sales do not correspond to high customers**?

## Inventory & Returns Analysis
11. What is the **total inventory** across all stores?
12. Which store has the **highest inventory stock**?
13. How many stores have **inventory less than 1300 units**?
14. Which store has the **highest return rate** (returns ÷ inventory)?
15. Which stores have **returns greater than 15 units**?

## Sales & Customer Correlation
16. Is there a **positive correlation** between sales and customers?
17. Which store has **high customer visits but low sales**?
18. Which store has **low customers but high sales**?
19. How many stores have **sales per customer above ₹90**?
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

## Profitability & Growth
21. If profit margin is **20% of sales**, what is the **profit per store**?
22. Which store has the **highest profit**?
23. Which store has the **lowest profit**?
24. If sales increase by **10% next month**, what are the **new sales figures**?
25. How will **total profit** change with the 10% sales increase?

## Operational Strategy
26. Which stores need **inventory restocking** based on sales and current stock?
27. Which stores show **high returns percentage** and might require **quality checks**?
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
29. Which store is the **worst performer overall**?
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?


In [ ]:
# 1. What is the **total revenue** generated across all stores?
retail_data[:,4].sum()

np.int64(142)

In [ ]:
#2.Which store recorded the **highest sales**?
retail_data[:,1].argmax()+1

np.int64(9)

In [ ]:
# 3. Which store recorded the **lowest sales**??
retail_data[:,1].argmin()+1

np.int64(1)

In [ ]:
# 4. What is the **average daily sales** per store?
retail_data[:,1].mean()

np.float64(33500.0)

In [ ]:
# 5. How many stores achieved sales **above ₹35,000**?
sales=retail_data[:,1]
count_above_35k=np.sum(sales>35000)
print(count_above_35k)


3


In [ ]:
# 6. Which store had the **highest customer footfall**?
retail_data[:,2].argmax()+1

np.int64(9)

In [ ]:
# 7. What is the **average number of customers** per store?
retail_data[:,2].mean()

np.float64(425.0)

In [ ]:
# 8. How many stores have **more than 450 customers**?
customers=retail_data[:,2]
count_above_450=np.sum(customers>450)
print(count_above_450)



3


In [ ]:
retail_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [ ]:
# 9. Which store has the **lowest customer count**?
retail_data[:,2].argmin()+1

np.int64(1)

In [ ]:
# 10. Is there any store where **high sales do not correspond to high customers**?
sal=retail_data[:,1].mean()
cus=retail_data[:,2].mean()
store=retail_data[(retail_data[:,1]>sal)&(retail_data[:,2]<cus)]
store


array([[    5, 35000,   420,  1400,    12]])

In [ ]:
# 11. What is the **total inventory** across all stores?
retail_data[:,3].sum()

np.int64(14300)

In [ ]:
# 12. Which store has the **highest inventory stock**?
retail_data[:,3].argmax()+1


np.int64(9)

In [ ]:
# 13. How many stores have **inventory less than 1300 units**?
inv=retail_data[:,3]
count_below_1300=np.sum(inv<1300)
print(count_below_1300)

3


In [ ]:
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
(retail_data[:,4]/retail_data[:,3]).argmax()+1

np.int64(9)

In [ ]:
# 15. Which stores have **returns greater than 15 units**?
returns=retail_data[:,4]
count_greater_15=np.sum(returns>15)
print(count_greater_15)


3


In [ ]:
# 16. Is there a **positive correlation** between sales and customers?
np.corrcoef(retail_data[:,1],retail_data[:,2])

array([[1.        , 0.95936369],
       [0.95936369, 1.        ]])

In [ ]:
# 17. Which store has **high customer visits but low sales**?
cus=retail_data[:,2].mean()
sal=retail_data[:,1].mean()
store=retail_data[(retail_data[:,2] > cus) & (retail_data[:,1] < sal)]
store


array([[    2, 32000,   450,  1500,    15]])

In [ ]:
# 18. Which store has **low customers but high sales**?
cus=retail_data[:,2].mean()
sal=retail_data[:,1].mean()
store=retail_data[(retail_data[:,2] < cus) & (retail_data[:,1] > sal)]
store

array([[    5, 35000,   420,  1400,    12]])

In [ ]:
# 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
cus=retail_data[:,2].mean()
inv=retail_data[:,3].mean()
store=retail_data[(retail_data[:,2]< cus) & (retail_data[:,3] > inv)]
store

array([[   10, 33000,   410,  1450,    11]])

In [ ]:
# 21. If profit margin is **20% of sales**, what is the **profit per store**?
sales=retail_data[:,1]
profit_per_store=sales*0.20
profit_per_store

array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [ ]:
# 22. Which store has the **highest profit**?
sales=retail_data[:,1]
profit_per_store=sales*0.20
max_store=np.argmax(profit_per_store)
max_store


np.int64(8)

In [ ]:
# 23. Which store has the **lowest profit**?
sales=retail_data[:,1]
profit__per_store=sales*0.20
min_store=np.argmin(profit_per_store)
min_store


np.int64(0)

In [4]:
print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# 24. If sales increase by **10% next month**, what are the **new sales figures**?
sales=retail_data[:,1]
new_sales=sales*1.10
new_sales

array([27500., 35200., 30800., 45100., 38500., 29700., 42900., 33000.,
       49500., 36300.])

In [ ]:
# 25. How will **total profit** change with the 10% sales increase?
old_profit=(sales*0.20).sum()
new_sales=sales*1.10
new_profit=(new_sales*0.20).sum()
profit_change=new_profit-old_profit
print(old_profit)
print(new_profit)
print(profit_change)

67000.0
73700.0
6700.0


In [ ]:
# 26. Which stores need **inventory restocking** based on sales and current stock?
sales=retail_data[:,1]
inv=retail_data[:,3]
store=retail_data[(sales > inv)]
store

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [10]:
# 27. Which stores show **high returns percentage** and might require **quality checks**?
sales=retail_data[:,1]
returns=retail_data[:,4]
returns_percentage=(returns/sales)*100
print(returns_percentage)
threshold=0.04
store_high_returns=retail_data[(returns_percentage > threshold)]
print(store_high_returns)




[0.04       0.046875   0.02857143 0.04878049 0.03428571 0.03333333
 0.04615385 0.04666667 0.05555556 0.03333333]
[[    2 32000   450  1500    15]
 [    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]]


In [16]:
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
sales=retail_data[:,1]
customers=retail_data[:,2]
inventory_turnover=retail_data[:,3]
best_performer_store=retail_data[np.argmax(sales+customers+inventory_turnover)]
print(best_performer_store)

[    9 45000   550  1800    25]


In [18]:
# 29. Which store is the **worst performer overall**?
worst_performer_store=retail_data[np.argmin(sales+customers+inventory_turnover)]
print(worst_performer_store)

[    1 25000   300  1200    10]


In [19]:
# 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
sales=retail_data[:,1]
customers=retail_data[:,2]
expansion_stores=retail_data[(sales > sales.mean()) & (customers > customers.mean())]
print(expansion_stores)

[[    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]]
